-- ============================================================================
-- TRAILMATE — curated season data: Andhra Pradesh & Telangana (19 places)
-- GENERATED from data/season-tags.json by scripts/build-season-migration.mjs — do not edit by hand;
-- edit the JSON and run `npm run build:season`. Safe to re-run (upserts by place name).
-- ============================================================================

insert into public.season_tags
  (place_name, lat, lng, category, good_months, reason, region, confidence, source_urls, last_checked)
values
  ('Undavalli Caves', 16.4962, 80.5835, 'museum', array[10, 11, 12, 1, 2, 3]::int[], 'Comfortable in the cool, dry months. The rock-cut caves turn warm and humid in summer, and the monsoon brings heavy rain.', 'Andhra Pradesh', 'researched', array['https://housing.com/news/places-to-visit-in-vijayawada-for-a-mesmerising-experience', 'https://www.holidify.com/places/vijayawada', 'https://championtraveler.com/dates/best-time-to-visit-vijayawada-in/']::text[], '2026-10-06'::date),
  ('Kondapalli Fort', 16.619, 80.534, 'fort', array[10, 11, 12, 1, 2, 3]::int[], 'The hilltop climb is pleasant in the cooler months and very hot in summer.', 'Andhra Pradesh', 'researched', array['https://housing.com/news/places-to-visit-in-vijayawada-for-a-mesmerising-experience', 'https://www.bajajfinserv.in/best-places-to-visit-in-vijayawada', 'https://championtraveler.com/dates/best-time-to-visit-vijayawada-in/']::text[], '2026-10-06'::date),
  ('Bhavani Island', 16.523, 80.599, 'lake', array[10, 11, 12, 1, 2, 3]::int[], 'The cool season suits the riverside island. When the Krishna swells in the monsoon, water activities can be limited.', 'Andhra Pradesh', 'researched', array['https://housing.com/news/places-to-visit-in-vijayawada-for-a-mesmerising-experience', 'https://championtraveler.com/dates/best-time-to-visit-vijayawada-in/']::text[], '2026-10-06'::date),
  ('Kanaka Durga Temple', 16.5155, 80.6054, 'temple', array[10, 11, 12, 1, 2, 3]::int[], 'Pleasant weather from October to March. Dussehra in autumn is the big festival, so expect crowds then.', 'Andhra Pradesh', 'researched', array['https://housing.com/news/places-to-visit-in-vijayawada-for-a-mesmerising-experience', 'https://www.onnbikes.com/blog/top-10-famous-temples-in-vijayawada-you-must-visit']::text[], '2026-10-06'::date),
  ('Kolleru Lake', 16.65, 81.2, 'wildlife', array[11, 12, 1, 2, 3]::int[], 'Migratory birds fill the lake in winter. The peak is roughly December to February.', 'Andhra Pradesh', 'researched', array['https://www.outlooktraveller.com/experiences/nature/a-million-strong-the-kolleru-lake-bird-sanctuary-in-andhra-pradesh', 'https://traveltriangle.com/blog/kolleru-lake/', 'https://thebetterindia.com/394231/best-birdwatching-destinations-india-winter-migration-rajasthan-gujarat-kerala']::text[], '2026-10-06'::date),
  ('Araku Valley', 18.3273, 82.8776, 'hill_station', array[10, 11, 12, 1, 2]::int[], 'Cool, clear and green after the monsoon. During heavy rain the ghat roads carry landslide and closure risk.', 'Andhra Pradesh', 'researched', array['https://www.holidify.com/places/araku-valley/best-time-to-visit.html', 'https://www.veenaworld.com/blog/places-to-visit-araku-valley', 'https://www.outlooktraveller.com/destinations/india/offbeat-hillstations-to-visit-in-andhra-pradesh']::text[], '2026-10-06'::date),
  ('Borra Caves', 18.2806, 82.9719, 'museum', array[10, 11, 12, 1, 2]::int[], 'Comfortable in the cool season, and nearby waterfalls flow strongest just after the monsoon (October to December).', 'Andhra Pradesh', 'researched', array['https://www.outlooktraveller.com/destinations/india/offbeat-wonders-lesser-known-destinations-near-visakhapatnam', 'https://www.veenaworld.com/blog/places-to-visit-araku-valley']::text[], '2026-10-06'::date),
  ('Lambasingi', 17.8667, 82.4833, 'hill_station', array[11, 12, 1, 2]::int[], 'Known for cold, misty winter mornings. It is one of the coolest spots in the state.', 'Andhra Pradesh', 'researched', array['https://www.outlooktraveller.com/destinations/india/offbeat-hillstations-to-visit-in-andhra-pradesh', 'https://www.siasat.com/4-lesser-known-andhra-pradesh-getaways-to-take-from-hyderabad-3538851/']::text[], '2026-10-06'::date),
  ('Papikondalu Boat Cruise', 17.5, 81.35, 'activity', array[10, 11, 12, 1, 2, 3]::int[], 'Boat trips are usually suspended when the Godavari floods in the monsoon (about July to September). Peak season runs from October to January.', 'Andhra Pradesh', 'researched', array['https://www.telangana360.com/2026/07/pochavaram-boating-point.html', 'https://www.deccanchronicle.com/southern-states/andhra-pradesh/tourism-boat-operations-to-papikondalu-remain-suspended-since-july-29-1987073', 'https://traveltriangle.com/blog/papikondalu/']::text[], '2026-10-06'::date),
  ('Bogatha Waterfall', 18.4761, 80.5, 'waterfall', array[6, 7, 8, 9, 10, 11]::int[], 'Water flows through the year, but the fall is fullest from June to November.', 'Telangana', 'researched', array['https://en.wikipedia.org/wiki/Bogatha_Waterfall', 'https://traveltriangle.com/blog/waterfalls-near-hyderabad/']::text[], '2026-10-06'::date),
  ('Kuntala Waterfall', 19.285, 78.503, 'waterfall', array[7, 8, 9, 10, 11, 12]::int[], 'Strongest in the monsoon and still good afterwards. The rocks are very slippery in heavy rain, so October to December is easier.', 'Telangana', 'researched', array['https://en.wikipedia.org/wiki/Kuntala_Waterfall', 'https://www.sotc.in/blog/?p=8517', 'https://telanganatourism.gov.in/partials/about/33-districts-of-telangana/adilabad.html', 'https://www.oyorooms.com/travel-guide/waterfalls-near-hyderabad/amp/']::text[], '2026-10-06'::date),
  ('Golconda Fort', 17.3833, 78.4011, 'fort', array[10, 11, 12, 1, 2, 3]::int[], 'Cooler months make the hill climb comfortable. Summer afternoons are very hot.', 'Telangana', 'researched', array['https://championtraveler.com/dates/best-time-to-visit-hyderabad-in/', 'https://www.thomascook.in/india-tourism/hyderabad-tourism/best-time-to-visit-hyderabad', 'https://www.indianholiday.com/telangana/hyderabad/best-time-to-visit.html']::text[], '2026-10-06'::date),
  ('Charminar', 17.3616, 78.4747, 'temple', array[10, 11, 12, 1, 2, 3]::int[], 'Walking the old city is easiest in the cooler months.', 'Telangana', 'researched', array['https://championtraveler.com/dates/best-time-to-visit-hyderabad-in/', 'https://www.thomascook.in/india-tourism/hyderabad-tourism/best-time-to-visit-hyderabad', 'https://www.indianholiday.com/telangana/hyderabad/best-time-to-visit.html']::text[], '2026-10-06'::date),
  ('Warangal Fort', 17.9497, 79.6015, 'fort', array[10, 11, 12, 1, 2, 3]::int[], 'Open ruins with little shade, so the cooler months are far more comfortable.', 'Telangana', 'researched', array['https://housing.com/news/places-to-visit-in-warangal-and-things-to-do', 'https://www.makemytrip.com/tripideas/places/warangal', 'https://traveltriangle.com/blog/places-to-visit-near-warangal/']::text[], '2026-10-06'::date),
  ('Thousand Pillar Temple', 18, 79.58, 'temple', array[10, 11, 12, 1, 2, 3]::int[], 'Best in the cooler months, between the end of the monsoon and the start of summer.', 'Telangana', 'researched', array['https://housing.com/news/places-to-visit-in-warangal-and-things-to-do', 'https://www.makemytrip.com/tripideas/places/warangal', 'https://traveltriangle.com/blog/places-to-visit-near-warangal/']::text[], '2026-10-06'::date),
  ('Ramappa Temple', 18.2594, 79.943, 'temple', array[10, 11, 12, 1, 2, 3]::int[], 'Best in the cooler months, between the end of the monsoon and the start of summer.', 'Telangana', 'researched', array['https://housing.com/news/places-to-visit-in-warangal-and-things-to-do', 'https://www.makemytrip.com/tripideas/places/warangal', 'https://traveltriangle.com/blog/places-to-visit-near-warangal/']::text[], '2026-10-06'::date),
  ('Gandikota', 14.814, 78.2842, 'viewpoint', array[10, 11, 12, 1, 2]::int[], 'Pleasant for the gorge views and camping. Summers are extremely hot and the monsoon makes paths slippery.', 'Andhra Pradesh', 'researched', array['https://natureinfocus.in/guide/gandikota/', 'https://www.siasat.com/4-lesser-known-andhra-pradesh-getaways-to-take-from-hyderabad-3538851/', 'https://muddietrails.com/?p=7329']::text[], '2026-10-06'::date),
  ('Belum Caves', 15.1, 78.117, 'museum', array[11, 12, 1, 2]::int[], 'The cave interior stays humid, so the cooler months are most comfortable.', 'Andhra Pradesh', 'researched', array['https://www.siasat.com/4-lesser-known-andhra-pradesh-getaways-to-take-from-hyderabad-3538851/', 'https://natureinfocus.in/guide/gandikota/']::text[], '2026-10-06'::date),
  ('RK Beach Visakhapatnam', 17.714, 83.323, 'beach', array[12, 1, 2, 3, 4]::int[], 'Little rain and not too hot from December to April.', 'Andhra Pradesh', 'researched', array['https://media.lonelyplanet.com/shop/pdfs/india-17-telangana-andhra-pradesh-preview.pdf']::text[], '2026-10-06'::date)
on conflict (lower(place_name)) do update set
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  good_months = excluded.good_months,
  reason = excluded.reason,
  region = excluded.region,
  confidence = excluded.confidence,
  source_urls = excluded.source_urls,
  last_checked = excluded.last_checked;
